/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Area} from './area';
import {Audit} from './audit';
import {Department} from './department';
import {Group} from './group';
import {Responsable} from './responsable';
import {Tag} from './tag';
import {Url} from './url';
import {Integration} from './integration';

export interface Asset {
  alias?: string;
  area?: Area;
  audits?: Array<Audit>;
  authentication?: number;
  authorization?: number;
  availability?: number;
  _class?: number;
  confidenciality?: number;
  department?: Department;
  description?: string;
  groups?: Array<Group>;
  hgf?: string;
  id?: number;
  integrity?: number;
  integrations?: Array<Integration>;
  location?: number;
  name?: string;
  responsables?: Array<Responsable>;
  risk?: number;
  status?: number;
  statusDate?: string;
  tags?: Array<Tag>;
  trazability?: number;
  urls?: Array<Url>;
  visibility?: number;
  volumetry?: number;
}
