/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Asset } from './asset';
import { Url } from './url';
import { Vulnerability } from './vulnerability';

export interface Audit { 
    asset?: Asset;
    _class?: string;
    delivered?: number;
    id?: number;
    launched?: string;
    methodology?: number;
    name?: string;
    notes?: string;
    risk?: number;
    scheduled?: string;
    status?: number;
    tool?: string;
    url?: Url;
    vtc?: number;
    vth?: number;
    vtm?: number;
    vtl?: number;
    vti?: number;
    vfc?: number;
    vfh?: number;
    vfm?: number;
    vfl?: number;
    vfi?: number;
    vac?: number;
    vah?: number;
    vam?: number;
    val?: number;
    vai?: number;
    vulnerabilities?: Array<Vulnerability>;
}