/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body2 { 
    asset: number;
    _class: number;
    delivered: number;
    launched: string;
    methodology: number;
    notes?: string;
    risk?: number;
    scheduled: string;
    status: number;
    tool: string;
    url?: number;
}