/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body4 { 
    accessDescription?: string;
    activityDescription?: string;
    activityLogs?: number;
    addUrls?: Array<string>;
    addEnv?: Array<string>;
    addPort?: Array<number>;
    alerts?: number;
    alias?: string;
    area?: number;
    authenLogs?: number;
    authentication?: number;
    authorization?: number;
    availability?: number;
    _class?: number;
    confidenciality?: number;
    description?: string;
    deleteUrls?: Array<number>;
    envs?: Array<string>;
    gcu?: number;
    gcuDescription?: string;
    hgf?: string;
    ids?: Array<number>;
    integrity?: number;
    modifyId?: Array<number>;
    modifyUrls?: Array<string>;
    modifyEnv?: Array<string>;
    modifyPort?: Array<number>;
    name?: string;
    pDelivery?: number;
    pExplotation?: number;
    pHosting?: number;
    ports?: Array<number>;
    rArea?: number;
    rDelivery?: number;
    reports?: number;
    rExplotation?: number;
    rFunctionality?: number;
    status?: number;
    trazability?: number;
    url?: Array<string>;
    visibility?: number;
}