/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body5 { 
    accessDescription?: string;
    activityDescription?: string;
    activityLogs?: number;
    alerts?: number;
    alias?: string;
    area: number;
    authenLogs?: number;
    authentication?: number;
    authorization?: number;
    availability?: number;
    _class: number;
    confidenciality?: number;
    description?: string;
    gcu?: number;
    gcuDescription?: string;
    hgf?: string;
    integrity?: number;
    name: string;
    pDelivery?: number;
    pExplotation?: number;
    pHosting?: number;
    rArea?: number;
    rDelivery?: number;
    reports?: number;
    rExplotation?: number;
    rFunctionality?: number;
    status?: number;
    url?: Array<string>;
    envs?: Array<string>;
    ports?: Array<number>;
    ids?: Array<number>;
    trazability?: number;
    visibility: number;
}