/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body14 { 
    addAreas?: number;
    addAssets?: number;
    addAudits?: number;
    addCompanies?: number;
    addGroups?: number;
    addNetworks?: number;
    addProfiles?: number;
    addProviders?: number;
    addResponsables?: number;
    addUrls?: number;
    addUsers?: number;
    addVulnerabilities?: number;
    admin?: number;
    assumeVulnerabilities?: number;
    closeVulnerabilities?: number;
    deleteAreas?: number;
    deleteAssets?: number;
    deleteAudits?: number;
    deleteCompanies?: number;
    deleteGroups?: number;
    deleteNetworks?: number;
    deleteProfiles?: number;
    deleteProviders?: number;
    deleteResponsables?: number;
    deleteUrls?: number;
    deleteUsers?: number;
    deleteVulnerabilities?: number;
    falsepositiveVulnerabilities?: number;
    getAreas?: number;
    getAssets?: number;
    getAudits?: number;
    getCompanies?: number;
    getGroups?: number;
    getNetworks?: number;
    getProfiles?: number;
    getProviders?: number;
    getResponsables?: number;
    getUrls?: number;
    getUsers?: number;
    getVulnerabilities?: number;
    modifyAreas?: number;
    modifyAssets?: number;
    modifyAudits?: number;
    modifyCompanies?: number;
    modifyGroups?: number;
    modifyNetworks?: number;
    modifyProfiles?: number;
    modifyProviders?: number;
    modifyResponsables?: number;
    modifyUrls?: number;
    modifyUsers?: number;
    modifyVulnerabilities?: number;
    name: string;
    openVulnerabilities?: number;
    reviewVulnerabilities?: number;
    viewAll?: number;
}