/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Area } from './area';
import { Group } from './group';

export interface Company { 
    id?: number;
    areas?: Array<Area>;
    description?: string;
    groups?: Array<Group>;
    name?: string;
}