/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Asset} from './asset';
import {Company} from './company';
import {User} from './user';

export interface Group {
  id?: number;
  assets?: Array<Asset>;
  company?: Company;
  description?: string;
  name?: string;
  users?: Array<User>;
}
