/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Asset} from './asset';

export interface Integration {
  id?: number;
  asset?: Asset;
  _class?: number;
  comment?: string;
  ndone?: number;
  ntotal?: number;
  papDate?: string;
  status?: number;
  startDate?: string;
}
