/**
 * IndexOf API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Group } from './group';
import { Profile } from './profile';
import { Company } from './company';

export interface User { 
    id?: number;
    groups?: Array<Group>;
    companies? : Array<Company>;
    password?: string;
    profile?: Profile;
    name?: string;
}